### ISSUE TITLE
gnome clock is unreadable

### ISSUE THREAD

**Issue by vitaminless** [snwh/paper-gtk-theme#162]
I am talking about http://live.gnome.org/GnomeClocks.
The problem is the background is light grey and the text is white, there is not engouh contrast to read it.
![gnome-clock-unreadable-with-paper](https://cloud.githubusercontent.com/assets/499420/7504752/f687f8c0-f44c-11e4-812a-9dd7835545b7.png)

I also noticed that the buttons to select the week day not showing any difference either they are active or inactive.

Anyways, thanks for this great theme!

**Comment by vitaminless** [comment]
I would fix it, but I don't know how.

**Comment by snwh** [comment]
I know. There are some custom widgets in the Clock that are picky.

**Comment by vitaminless** [comment]
I found out that the css
```css
ClocksWindow .clocks-digital-renderer.active.stripe,
ClocksWindow .clocks-digital-renderer.snoozing.stripe,
ClocksWindow .clocks-digital-renderer.inactive.stripe {
    background-color: transparent;
    background-image: none;
}
```
should do the trick, but certainly not does.

The background-color property should not be transparent, anyway setting it to any value doesn't work.
When I use the Gtk+ Inspector and add this as custom rule it works (at least after one hover), wonder why.

I checked some other themes and recognized that nobody seems to tried before.
Did you ever seen this done before?

I also find it really hard to find resources as my background is not theming at all, usally other people do this for me. Maybe you can give me a hint.

**Comment by vitaminless** [comment]
Well forget about my last comment ... I think I have a solution!

I tried to set colors
```css
@define-color clocks_alarm_active #4BAE4F;
.clocks-digital-renderer.active {
    background-color: transparent;
    background-image: -gtk-gradient(radial,
      center center, 0,
      center bottom, 1.0,
      from(shade(@clocks_alarm_active,1.2)), to(@clocks_alarm_active));
    color: white;
}

.clocks-digital-renderer.active:prelight {
    background-color: transparent;
    background-image: -gtk-gradient(radial,
      center center, 0,
      center bottom, 1.0,
      from(shade(@clocks_alarm_active, 1.4)), to(@clocks_alarm_active));
    text-shadow: 0 2px 2px rgba(0,0,0,0.5)
}

@define-color clocks_alarm_snoozing #E4991B;
.clocks-digital-renderer.snoozing {
    background-color: transparent;
    background-image: -gtk-gradient(radial,
      center center, 0,
      center bottom, 1.0,
      from(@clocks_alarm_snoozing), to(shade(@clocks_alarm_snoozing,0.9)));
    color: white;
}

.clocks-digital-renderer.snoozing:prelight {
    background-color: transparent;
    background-image: -gtk-gradient(radial,
      center center, 0,
      center bottom, 1.0,
      from(shade(@clocks_alarm_snoozing,0.9)), to(shade(@clocks_alarm_snoozing,0.85)));
    text-shadow: 0 2px 2px rgba(0,0,0,0.5)
}

@define-color clocks_alarm_inactive #758387;
.clocks-digital-renderer.inactive {
    background-color: transparent;
    background-image: -gtk-gradient(radial,
      center center, 0,
      center bottom, 1.0,
      from(shade(@clocks_alarm_inactive,0.9)), to(shade(@clocks_alarm_inactive,0.85)));
    color: shade(@insensitive_fg_color,0.9);
}

.clocks-digital-renderer.inactive:prelight {
    background-color: transparent;
    background-image: -gtk-gradient(radial,
      center center, 0,
      center bottom, 1.0,
      from(shade(@clocks_alarm_inactive,0.99)), to(shade(@clocks_alarm_inactive,0.9)));
    color: @insensitive_fg_color;
}
```
which _doesn't_ work at all.

I check the inspector a noted that these rules are never loaded.

So I just tried to use the default rules and set following colors:
```css
@define-color theme_selected_bg_color #4BAE4F;
@define-color warning_color #E4991B;
@define-color insensitive_bg_color #758387;
```
and it works charming ... that is akward!

So I still have a request, can you please set up the colors to match the theme, I am partly color blind so it is nearly impossible for me to do so...

I will try to check also the buttons for weekdays in the alarm set up dialog.
