### ISSUE TITLE
Is this a bug or... [Gnome Archive]

### ISSUE THREAD

**Issue by kimamb** [snwh/paper-gtk-theme#216]
Is that gray part supposed to be... grey? (since brown would be more appropriate)

![screenshot from 2015-08-31 17-30-11](https://cloud.githubusercontent.com/assets/10121762/9582511/0ed39dac-5006-11e5-8c5d-ccad9aa3335a.png)

A theory I have is that you don't have control over that part, if this is true just remove/flag this post

**Comment by snwh** [comment]
I'm uncertain, I'd have to poke around in the GTK of the archive utility to determine if I can make it match.

**Comment by kimamb** [comment]
It isn't that bad to look at, but it looks a bit weird.


Thank you

**Comment by snwh** [comment]
"Looks a bit weird indeed"

**Comment by bil-elmoussaoui** [comment]
What about this result? 
![screenshot from 2015-12-17 13-49-01](https://cloud.githubusercontent.com/assets/7660997/11870096/f2b6dc4c-a4c4-11e5-82ce-058bcde5aae8.png)

This is what i added to `archive-manager.css`
```css
FrWindow FrLocationBar {
background-color:@archives;
}

FrWindow FrLocationBar GtkEntry{
background-color:shade(@archives, 0.9);
}
```

**Comment by kimamb** [comment]
@bil-elmoussaoui Awesome!

**Comment by bil-elmoussaoui** [comment]
The same bug is in Contacts too
![screenshot from 2015-12-17 13-55-45](https://cloud.githubusercontent.com/assets/7660997/11870215/ef4c4d02-a4c5-11e5-9bba-9999e4e2a529.png)
Adding those to `gonme-contacts.css`
```css

ContactsWindow GtkToolbar{
    background-color: shade(@contacts,0.9);
}
ContactsWindow GtkSearchEntry {
    background-color: shade(@contacts,0.9);
color:white;
}
```
"Will fix it"
![screenshot from 2015-12-17 13-56-03](https://cloud.githubusercontent.com/assets/7660997/11870216/ef4e1c5e-a4c5-11e5-936f-d3c8fb00a163.png)

@snwh Do you think that i should open a PR or it's not the proper way to fix it? :)
