### ISSUE TITLE
Elementary OS Freya Beta 2 White text on white background issue

### ISSUE THREAD

**Issue by RonCan** [snwh/paper-gtk-theme#80]
Alright so my issue looks like https://github.com/snwh/paper-gtk-theme/issues/27 this one but that has been closed saying it has been fixed. I just installed Paper from the daily ppa and I can't see the text on Power or volume or any drop down.

**Comment by MEdward** [comment]
I fixed this issue by modifying this file Paper/gtk-3.0/widgets/menubars.css at line 103 this:

```css
.menubar .menuitem:backdrop GtkLabel,
.menubar .menuitem:backdrop:hover GtkLabel,
.menubar .menuitem:active:backdrop GtkLabel {
    color: @backdrop_header_text;
}
```
into this:
```css
.menubar .menuitem:backdrop GtkLabel,
.menubar .menuitem:active:backdrop GtkLabel {
    color: @backdrop_header_text;
}

.menubar .menuitem:backdrop:hover GtkLabel {
    color: @backdrop_text;
    /* color: alpha (#000, 0.6); */
}
```

If the text is too washed, use the color value from the commented color line.
